# Generated by Django 6.0.8 on 2026-09-03 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('auth_provider', models.CharField(default='email', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_legit', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('total_received', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('withdraw_bank_account_number', models.CharField(blank=True, max_length=50)),
                ('withdraw_bank_account_name', models.CharField(blank=True, max_length=100)),
                ('withdraw_bank_code', models.CharField(blank=True, max_length=20)),
                ('bank_code', models.CharField(max_length=20)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['is_legit', 'is_active'], name='user_page_is_legi_6a21b8_idx')],
            },
        ),
    ]
