# Generated by Django 6.0.8 on 2026-09-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='bank_code',
        ),
    ]
