"""
Django settings for AppDonate project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from .env_config import env
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'notification',
    'user',
    'order',
    'relationship',
    'cacheops',
    'silk',
    'corsheaders',
    # Phần bảo mật
    'django.contrib.sites',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'axes',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'csp',
    'django_pwned_passwords',
    # safe delete
    'safedelete',
    # django-channels ỏ
    'channels',
    # elastic search
    'django_elasticsearch_dsl',
    # celery
    'django_celery_beat',
    'django_celery_results',
    # django cleanup, cuối
    "django_cleanup.apps.CleanupConfig",
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware', # nén file truyền qua internet để nhẹ
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # whitenoise
    "csp.middleware.CSPMiddleware",#csp
    'corsheaders.middleware.CorsMiddleware',# corsheader
    'silk.middleware.SilkyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',  # axes
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',#allauth
]

ROOT_URLCONF = 'AppDonate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AppDonate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "dj_db_conn_pool.backends.mysql", #dùng engine của connection pool
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env('DB_PASSWORD'),
        "HOST": env('DB_HOST', default='percona'),
        "PORT": env('DB_PORT', default='3306'),

        # # Performance, pool options lo nên tắt hết
        # "CONN_MAX_AGE": 0,  # tái sử dụng cổng đã mở, tái sử dụng connection lâu hơn
        # "CONN_HEALTH_CHECKS": False,  # kiểm tra connection còn sống không trước khi dùng

        # Connection pool dùng để tái sử dụng các connection mà k cần tạo mới mỗi request
        "POOL_OPTIONS": { #số pool có sẵn là 20, khi chưa dùng hết thì dùng lại, khi hết thì mở thêm và tối đa mở 30
            "POOL_SIZE": 20,  # số connection pool
            "MAX_OVERFLOW": 10,  # connection thêm khi pool đầy
            "RECYCLE": 3600,  # recycle connection sau 5 phút
            "TIMEOUT": 60,  # chờ tối đa 30s lấy connection từ pool
            "POOL_PRE_PING": True, #check xem connection còn sống không
            'isolation_level': 'read committed', # đảm bảo tính nhất quán trong transaction tránh đọc data cũ
        },

        "OPTIONS": {
            # SQL mode chuẩn production
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'",

            "charset": "utf8mb4",  # support emoji, ký tự đặc biệt

            # Giảm latency kết nối
            "connect_timeout": 5,

            # SSL — bật nếu DB ở server khác giúp mã hóa dữ liệu truyền qua mạng
            # "ssl": {
            #     "ca": "/path/to/ca-cert.pem",
            # },
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "pwned_passwords_django.validators.PwnedPasswordsValidator",  # pwn_password

    },
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#lưu ảnh
MEDIA_ROOT=os.path.join(BASE_DIR,'media') #basedir là tìm trong thư mục gốc có media
MEDIA_URL='/media/' #ví dụ media/abc.jpg

# Platform Bank Configuration for QR Code Generation
PLATFORM_BANK_CODE = env('PLATFORM_BANK_CODE', default='MB')
PLATFORM_BANK_ACCOUNT = env('PLATFORM_BANK_ACCOUNT', default='123456789')
PLATFORM_BANK_ACCOUNT_NAME = env('PLATFORM_BANK_ACCOUNT_NAME', default='NGUYEN VAN A')

# SePay Money Transfer API (dùng cho chức năng rút tiền)
SEPAY_API_TOKEN = env('SEPAY_API_TOKEN', default='')
SEPAY_TRANSFER_URL = env('SEPAY_TRANSFER_URL', default='https://my.sepay.vn/api/v1/transfer')

# Celery Configuration
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://redis:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://redis:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

CELERY_BEAT_SCHEDULE = {
    'expire_pending_orders_every_5s': {
        'task': 'order.tasks.expire_pending_orders_task',
        'schedule': 5.0,
    },
}

from .settings_authentication import *