# Generated by Django 6.0.8 on 2026-09-03 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('user', '0002_remove_page_bank_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.page')),
                ('donater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['donater', 'created_at'], name='notificatio_donater_72950f_idx'), models.Index(fields=['donatee', 'created_at'], name='notificatio_donatee_1fca98_idx')],
            },
        ),
    ]
